# Generated by Django 5.0.7 on 2024-08-11 01:13

import goodmeal_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodmeal_app', '0010_alter_recipe_composites_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='composites',
            field=goodmeal_app.models.StrippingTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=goodmeal_app.models.StrippingTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
