# Generated by Django 5.0.7 on 2024-08-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodmeal_app', '0002_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
