# Generated by Django 5.0.7 on 2024-08-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodmeal_app', '0006_rename_recipe_recipe_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='composites',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
        ),
    ]
