# Generated by Django 5.0.7 on 2024-08-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodmeal_app', '0013_recommendedrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedrestaurant',
            name='restaurent_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
